version: '3.7'

services:
  svelte:
    image: svelte-template:dev
    build:
      context: .
    volumes:
      - ".:/app"
    ports:
      - "5000:5000"
      - "35729:35729"
    networks:
      - svelte
    environment: 
      - DKRENT_URL=https://api-eu.preprod.decathlon.net/dktrent/api/v1/sites/
      - GMAPS_KEY=AIzaSyBhajfNAGnRtcO-aBnNNknin_z017itOsM
  e2e:
    image: cypress/included:3.8.0
    working_dir: "/app"
    volumes:
      - ".:/app"
    networks:
      - svelte
  tests:
    image: node
    volumes:
      - ".:/app"
    working_dir: "/app"
    command: "npx babel-node tests/unit/run.js"

networks:
  svelte: